### ISSUE TITLE
Fill last used column in token list

### ISSUE THREAD

**Issue by spalte** [OsiriX-Foundation/KheopsUI#15]
The token resources now return this value. (last_used)
The version currently online calls this "last_use". This will be imminently fixed to "last_used"

**Comment by spalte** [comment]
last_used has been fixed

**Comment by rliechti** [comment]
this field is only available if the token has been used once. Right ?

Can you tell me how I could 'use' a token for testing ?

Thanks for your help.
--
Robin Liechti, PhD
SIB | Swiss Institute of Bioinformatics
Vital-IT
UNIL, Quartier Sorge, Bâtiment Amphipole - CH 1015 Lausanne

+41 21 692 40 80
