### ISSUE TITLE
Infinite scroll does not work on Safari

### ISSUE THREAD

**Issue by spalte** [OsiriX-Foundation/KheopsUI#17]

**Comment by spalte** [comment]
It doesn't work on Chrome on my iPhone either.

**Comment by spalte** [comment]
Or on Chrome on Android either

**Comment by spalte** [comment]
If the main screen accommodates more than the original 10 studies, the infinite scroll will never be triggered. This happens on iPad for example.

**Comment by spalte** [comment]
Now when the page is large enough to hold more than 5 studies, the infinite scroll is never triggered

**Comment by rliechti** [comment]
Hello Joël,

Would it be possible to add more studies to my inbox so that it would be easier for me to debug the infinite-scroll ?

Thanks,

Robin
--
Robin Liechti, PhD
SIB | Swiss Institute of Bioinformatics
Vital-IT
UNIL, Quartier Sorge, Bâtiment Amphipole - CH 1015 Lausanne

+41 21 692 40 80
