### ISSUE TITLE
Update Dependecies with security vulnerabilities

### ISSUE THREAD

**Issue by nicolasvandooren** [OsiriX-Foundation/KheopsUI#2]
Github give a warning for Jquery and webpack-dev-server.

**Comment by rliechti** [comment]
I have started to migrate the project to version 3 of vue-cli. Like always, these automagic tools should never be updated... I am trying to identify what has dramatically changed

**Comment by rliechti** [comment]
I have pushed the migration du vue-cli3 to a new branch. Vue-CLI3 runs a bit differently to Vue-CLI2. Read README file to get an update.

**Comment by spalte** [comment]
We have other security vulnerabilities again
