### ISSUE TITLE
Hide new token button in album settings panel for non-admins

### ISSUE THREAD

**Issue by spalte** [OsiriX-Foundation/KheopsUI#42]
Only Album admins are allowed hold album tokens, so we should not allow them to create new tokens. They should still be able to any tokens they created while they were admins though (which will have been revoked)

**Comment by spalte** [comment]
Oops, already fixed

**Comment by rliechti** [comment]
Can you explain what is currently not working ? (why this task is back on the todo column) ? Thanks

**Comment by nicolasvandooren** [comment]
I think I made a wrong manipulation for this task ...
Sorry.
