### ISSUE TITLE
When we come back to the previous page, the page Studies and Setting is empty

### ISSUE THREAD

**Issue by nicolasvandooren** [OsiriX-Foundation/KheopsUI#46]
If you navigate like that in an album :
Study -> Setting/General -> User
The page Setting/General and Study are empty.

When the url doesn't have the query parameters, the page is empty :
albums/xxxxx - Empty page
/albums/xxxxx?view=studies - Fill page

**Comment by nicolasvandooren** [comment]
The navigation have still the problem when I make :
albumId?view=settings&cat=user -> albumId?view=settings
The page "General" is empty.

albumId?view=comments -> albumId?view=studies -> albumId
The last URL doesn't have the query parameters.

**Comment by rliechti** [comment]
I have fixed these two issues
