### ISSUE TITLE
During a request, wait response before to resend

### ISSUE THREAD

**Issue by gerome12** [OsiriX-Foundation/KheopsUI#62]
When an action / request is in progress, the button or the element that
triggered it must be desactived.

In this case:

- create album
- create token
- create/edit report provider
- create/edit webhook

Verify on add user in an album and send a study to user.

**Comment by nicolasvandooren** [comment]
Add a spinner to specify to the user that loading is in progress.

On add user must wait too.

**Comment by nicolasvandooren** [comment]
On delete must wait the response too
