### ISSUE TITLE
Update study list modality filter

### ISSUE THREAD

**Issue by gerome12** [OsiriX-Foundation/KheopsUI#80]
Quand on drag and drop des séries dans un album vide 

le filtre des modalités ne se mets pas à jour

**Comment by nicolasvandooren** [comment]
Lorsque je charge de nouvelles études dans un album, je dois utiliser la ressource /album pour récupérer la liste des modalités.
Est-ce qu'il serait possible d'avoir une ressource me permettant de récupérer la liste des modalités d'une source donnée ?

Par exemple /modalities?source=inbox/album_id

**Comment by nicolasvandooren** [comment]
Le problème est également présent lors de la suppression d'une étude, la liste des modalités ne se met pas à jours.
