### ISSUE TITLE
Do not unselect studies if the query produces an error 

### ISSUE THREAD

**Issue by gerome12** [OsiriX-Foundation/KheopsUI#83]

**Comment by nicolasvandooren** [comment]
What use case would be interesting to add this functionality?

**Comment by nicolasvandooren** [comment]
The solution to keep selected all the studies / series when an error occurs or to keep selected only the studies / series which produce an error risk losing the user. Especially currently with our unclear error messages, the temporary banner.

The best solution is to use the display box #63 to show the last action with success and error. The idea will be to propose to return the erroneous request or to select, to visualize the studies / series which produce the error.
